name: Code style check

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

jobs:
  job_lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Lint
        uses: DoozyX/clang-format-lint-action@c71d0bf4e21876ebec3e5647491186f8797fde31 # v0.15
        with:
          source: "./"
          extensions: "h,c"
          clangFormatVersion: 12.0.1
