name: Code style check

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

jobs:
  job_lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Lint
        uses: DoozyX/clang-format-lint-action@bcb4eb2cb0d707ee4f3e5cc3b456eb075f12cf73 # v0.20
        with:
          source: "./"
          extensions: "h,c"
          clangFormatVersion: 12.0.1
